swagger: '2.0'
info:
  title: 'User Authentication API'
  description: 'API endpoints for user registration, login, and token generation.'
  version: '1.0'
consumes:
  - 'application/json'
produces:
  - 'application/json'
paths:
  /register:
    post:
      summary: Register a new user
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            type: 'object'
            required:
              - username
              - password
            properties:
              username:
                type: 'string'
                description: 'Username of the user.'
              password:
                type: 'string'
                description: 'Password of the user.'
      responses:
        '201':
          description: 'User registered successfully.'
        '400':
          description: 'Invalid request data.'

  /login:
    post:
      summary: User login
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            type: 'object'
            required:
              - username
              - password
            properties:
              username:
                type: 'string'
                description: 'Username of the user.'
              password:
                type: 'string'
                description: 'Password of the user.'
      responses:
        '200':
          description: 'Successful login.'
        '401':
          description: 'Invalid username or password.'

  /token:
    get:
      summary: Get access token
      produces:
        - 'application/json'
      security:
        - JWT: []
      responses:
        '200':
          description: 'Access token retrieved successfully.'
        '401':
          description: 'Unauthorized - Token is missing or invalid.'
