swagger: '2.0'
info:
  title: Token Refresh API
  description: API for refreshing an access token (if applicable).
  version: 1.0

security:
  bearerAuth: []  # Assuming JWT-based authentication

paths:
  /token:
    get:
      summary: Refresh access token
      description: Obtains a new access token if the current one is expiring.
      tags: [Token]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Token refreshed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: New JWT access token
        401:
          description: Unauthorized (invalid or missing token)
          content: {}
        500:
          description: Internal server error
          content: {}
